include:
  # Injects TMO Global Shared (handles certs, lists blacklisted files etc)
  - project: 'tmobile/automation-engineering/build'
    ref: tmo/sprint-20S25_TEQAE-3910
    file: '.tmo.job.ctp.gitlab_ci.yml'

variables:
  APP_VERSION: "0.0.11"
  ARTIFACT_ID: "codeless"
  GROUP_ID: "com/tmobile/ct"
  BUILD_TYPE: jar
  MAVEN_BUILD_ARGS: "install -DappVersion=${APP_VERSION} -Dartifactory.publish.artifacts=true -Dartifactory.publish.buildInfo=true"
